[build]
  command = "pip install -r requirements.txt"
  publish = ""

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/streamlit"
  status = 200
  force = false

[functions]
  directory = "netlify/functions"

[dev]
  command = "streamlit run app.py --server.port 8501 --server.address 0.0.0.0"

# Environment variables (set these in Netlify UI)
# GEMINI_API_KEY = "your-google-ai-studio-api-key" (optional)